/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-vsphere-api/apis/dpm/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHostOverrides implements HostOverrideInterface
type FakeHostOverrides struct {
	Fake *FakeDpmV1alpha1
	ns   string
}

var hostoverridesResource = schema.GroupVersionResource{Group: "dpm.vsphere.kubeform.com", Version: "v1alpha1", Resource: "hostoverrides"}

var hostoverridesKind = schema.GroupVersionKind{Group: "dpm.vsphere.kubeform.com", Version: "v1alpha1", Kind: "HostOverride"}

// Get takes name of the hostOverride, and returns the corresponding hostOverride object, and an error if there is any.
func (c *FakeHostOverrides) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HostOverride, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hostoverridesResource, c.ns, name), &v1alpha1.HostOverride{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HostOverride), err
}

// List takes label and field selectors, and returns the list of HostOverrides that match those selectors.
func (c *FakeHostOverrides) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HostOverrideList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hostoverridesResource, hostoverridesKind, c.ns, opts), &v1alpha1.HostOverrideList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HostOverrideList{ListMeta: obj.(*v1alpha1.HostOverrideList).ListMeta}
	for _, item := range obj.(*v1alpha1.HostOverrideList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hostOverrides.
func (c *FakeHostOverrides) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hostoverridesResource, c.ns, opts))

}

// Create takes the representation of a hostOverride and creates it.  Returns the server's representation of the hostOverride, and an error, if there is any.
func (c *FakeHostOverrides) Create(ctx context.Context, hostOverride *v1alpha1.HostOverride, opts v1.CreateOptions) (result *v1alpha1.HostOverride, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hostoverridesResource, c.ns, hostOverride), &v1alpha1.HostOverride{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HostOverride), err
}

// Update takes the representation of a hostOverride and updates it. Returns the server's representation of the hostOverride, and an error, if there is any.
func (c *FakeHostOverrides) Update(ctx context.Context, hostOverride *v1alpha1.HostOverride, opts v1.UpdateOptions) (result *v1alpha1.HostOverride, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hostoverridesResource, c.ns, hostOverride), &v1alpha1.HostOverride{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HostOverride), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHostOverrides) UpdateStatus(ctx context.Context, hostOverride *v1alpha1.HostOverride, opts v1.UpdateOptions) (*v1alpha1.HostOverride, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hostoverridesResource, "status", c.ns, hostOverride), &v1alpha1.HostOverride{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HostOverride), err
}

// Delete takes name of the hostOverride and deletes it. Returns an error if one occurs.
func (c *FakeHostOverrides) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hostoverridesResource, c.ns, name), &v1alpha1.HostOverride{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHostOverrides) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hostoverridesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HostOverrideList{})
	return err
}

// Patch applies the patch and returns the patched hostOverride.
func (c *FakeHostOverrides) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HostOverride, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hostoverridesResource, c.ns, name, pt, data, subresources...), &v1alpha1.HostOverride{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HostOverride), err
}
