/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-vsphere-api/apis/drs/v1alpha1"
	scheme "kubeform.dev/provider-vsphere-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// VmOverridesGetter has a method to return a VmOverrideInterface.
// A group's client should implement this interface.
type VmOverridesGetter interface {
	VmOverrides(namespace string) VmOverrideInterface
}

// VmOverrideInterface has methods to work with VmOverride resources.
type VmOverrideInterface interface {
	Create(ctx context.Context, vmOverride *v1alpha1.VmOverride, opts v1.CreateOptions) (*v1alpha1.VmOverride, error)
	Update(ctx context.Context, vmOverride *v1alpha1.VmOverride, opts v1.UpdateOptions) (*v1alpha1.VmOverride, error)
	UpdateStatus(ctx context.Context, vmOverride *v1alpha1.VmOverride, opts v1.UpdateOptions) (*v1alpha1.VmOverride, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.VmOverride, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.VmOverrideList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VmOverride, err error)
	VmOverrideExpansion
}

// vmOverrides implements VmOverrideInterface
type vmOverrides struct {
	client rest.Interface
	ns     string
}

// newVmOverrides returns a VmOverrides
func newVmOverrides(c *DrsV1alpha1Client, namespace string) *vmOverrides {
	return &vmOverrides{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vmOverride, and returns the corresponding vmOverride object, and an error if there is any.
func (c *vmOverrides) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VmOverride, err error) {
	result = &v1alpha1.VmOverride{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vmoverrides").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VmOverrides that match those selectors.
func (c *vmOverrides) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VmOverrideList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.VmOverrideList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vmoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vmOverrides.
func (c *vmOverrides) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vmoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vmOverride and creates it.  Returns the server's representation of the vmOverride, and an error, if there is any.
func (c *vmOverrides) Create(ctx context.Context, vmOverride *v1alpha1.VmOverride, opts v1.CreateOptions) (result *v1alpha1.VmOverride, err error) {
	result = &v1alpha1.VmOverride{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vmoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vmOverride).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vmOverride and updates it. Returns the server's representation of the vmOverride, and an error, if there is any.
func (c *vmOverrides) Update(ctx context.Context, vmOverride *v1alpha1.VmOverride, opts v1.UpdateOptions) (result *v1alpha1.VmOverride, err error) {
	result = &v1alpha1.VmOverride{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vmoverrides").
		Name(vmOverride.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vmOverride).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *vmOverrides) UpdateStatus(ctx context.Context, vmOverride *v1alpha1.VmOverride, opts v1.UpdateOptions) (result *v1alpha1.VmOverride, err error) {
	result = &v1alpha1.VmOverride{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vmoverrides").
		Name(vmOverride.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vmOverride).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vmOverride and deletes it. Returns an error if one occurs.
func (c *vmOverrides) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vmoverrides").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vmOverrides) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vmoverrides").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vmOverride.
func (c *vmOverrides) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VmOverride, err error) {
	result = &v1alpha1.VmOverride{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vmoverrides").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
