/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-vsphere-api/apis/storage/v1alpha1"
	scheme "kubeform.dev/provider-vsphere-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DrsVmOverridesGetter has a method to return a DrsVmOverrideInterface.
// A group's client should implement this interface.
type DrsVmOverridesGetter interface {
	DrsVmOverrides(namespace string) DrsVmOverrideInterface
}

// DrsVmOverrideInterface has methods to work with DrsVmOverride resources.
type DrsVmOverrideInterface interface {
	Create(ctx context.Context, drsVmOverride *v1alpha1.DrsVmOverride, opts v1.CreateOptions) (*v1alpha1.DrsVmOverride, error)
	Update(ctx context.Context, drsVmOverride *v1alpha1.DrsVmOverride, opts v1.UpdateOptions) (*v1alpha1.DrsVmOverride, error)
	UpdateStatus(ctx context.Context, drsVmOverride *v1alpha1.DrsVmOverride, opts v1.UpdateOptions) (*v1alpha1.DrsVmOverride, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.DrsVmOverride, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DrsVmOverrideList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DrsVmOverride, err error)
	DrsVmOverrideExpansion
}

// drsVmOverrides implements DrsVmOverrideInterface
type drsVmOverrides struct {
	client rest.Interface
	ns     string
}

// newDrsVmOverrides returns a DrsVmOverrides
func newDrsVmOverrides(c *StorageV1alpha1Client, namespace string) *drsVmOverrides {
	return &drsVmOverrides{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the drsVmOverride, and returns the corresponding drsVmOverride object, and an error if there is any.
func (c *drsVmOverrides) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DrsVmOverride, err error) {
	result = &v1alpha1.DrsVmOverride{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("drsvmoverrides").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DrsVmOverrides that match those selectors.
func (c *drsVmOverrides) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DrsVmOverrideList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DrsVmOverrideList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("drsvmoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested drsVmOverrides.
func (c *drsVmOverrides) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("drsvmoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a drsVmOverride and creates it.  Returns the server's representation of the drsVmOverride, and an error, if there is any.
func (c *drsVmOverrides) Create(ctx context.Context, drsVmOverride *v1alpha1.DrsVmOverride, opts v1.CreateOptions) (result *v1alpha1.DrsVmOverride, err error) {
	result = &v1alpha1.DrsVmOverride{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("drsvmoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(drsVmOverride).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a drsVmOverride and updates it. Returns the server's representation of the drsVmOverride, and an error, if there is any.
func (c *drsVmOverrides) Update(ctx context.Context, drsVmOverride *v1alpha1.DrsVmOverride, opts v1.UpdateOptions) (result *v1alpha1.DrsVmOverride, err error) {
	result = &v1alpha1.DrsVmOverride{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("drsvmoverrides").
		Name(drsVmOverride.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(drsVmOverride).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *drsVmOverrides) UpdateStatus(ctx context.Context, drsVmOverride *v1alpha1.DrsVmOverride, opts v1.UpdateOptions) (result *v1alpha1.DrsVmOverride, err error) {
	result = &v1alpha1.DrsVmOverride{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("drsvmoverrides").
		Name(drsVmOverride.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(drsVmOverride).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the drsVmOverride and deletes it. Returns an error if one occurs.
func (c *drsVmOverrides) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("drsvmoverrides").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *drsVmOverrides) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("drsvmoverrides").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched drsVmOverride.
func (c *drsVmOverrides) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DrsVmOverride, err error) {
	result = &v1alpha1.DrsVmOverride{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("drsvmoverrides").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
