/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-vsphere-api/apis/host/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePortGroups implements PortGroupInterface
type FakePortGroups struct {
	Fake *FakeHostV1alpha1
	ns   string
}

var portgroupsResource = schema.GroupVersionResource{Group: "host.vsphere.kubeform.com", Version: "v1alpha1", Resource: "portgroups"}

var portgroupsKind = schema.GroupVersionKind{Group: "host.vsphere.kubeform.com", Version: "v1alpha1", Kind: "PortGroup"}

// Get takes name of the portGroup, and returns the corresponding portGroup object, and an error if there is any.
func (c *FakePortGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PortGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(portgroupsResource, c.ns, name), &v1alpha1.PortGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PortGroup), err
}

// List takes label and field selectors, and returns the list of PortGroups that match those selectors.
func (c *FakePortGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PortGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(portgroupsResource, portgroupsKind, c.ns, opts), &v1alpha1.PortGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PortGroupList{ListMeta: obj.(*v1alpha1.PortGroupList).ListMeta}
	for _, item := range obj.(*v1alpha1.PortGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested portGroups.
func (c *FakePortGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(portgroupsResource, c.ns, opts))

}

// Create takes the representation of a portGroup and creates it.  Returns the server's representation of the portGroup, and an error, if there is any.
func (c *FakePortGroups) Create(ctx context.Context, portGroup *v1alpha1.PortGroup, opts v1.CreateOptions) (result *v1alpha1.PortGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(portgroupsResource, c.ns, portGroup), &v1alpha1.PortGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PortGroup), err
}

// Update takes the representation of a portGroup and updates it. Returns the server's representation of the portGroup, and an error, if there is any.
func (c *FakePortGroups) Update(ctx context.Context, portGroup *v1alpha1.PortGroup, opts v1.UpdateOptions) (result *v1alpha1.PortGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(portgroupsResource, c.ns, portGroup), &v1alpha1.PortGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PortGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePortGroups) UpdateStatus(ctx context.Context, portGroup *v1alpha1.PortGroup, opts v1.UpdateOptions) (*v1alpha1.PortGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(portgroupsResource, "status", c.ns, portGroup), &v1alpha1.PortGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PortGroup), err
}

// Delete takes name of the portGroup and deletes it. Returns an error if one occurs.
func (c *FakePortGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(portgroupsResource, c.ns, name), &v1alpha1.PortGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePortGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(portgroupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PortGroupList{})
	return err
}

// Patch applies the patch and returns the patched portGroup.
func (c *FakePortGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PortGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(portgroupsResource, c.ns, name, pt, data, subresources...), &v1alpha1.PortGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PortGroup), err
}
