/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-vsphere-api/apis/host/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeVirtualSwitches implements VirtualSwitchInterface
type FakeVirtualSwitches struct {
	Fake *FakeHostV1alpha1
	ns   string
}

var virtualswitchesResource = schema.GroupVersionResource{Group: "host.vsphere.kubeform.com", Version: "v1alpha1", Resource: "virtualswitches"}

var virtualswitchesKind = schema.GroupVersionKind{Group: "host.vsphere.kubeform.com", Version: "v1alpha1", Kind: "VirtualSwitch"}

// Get takes name of the virtualSwitch, and returns the corresponding virtualSwitch object, and an error if there is any.
func (c *FakeVirtualSwitches) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.VirtualSwitch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(virtualswitchesResource, c.ns, name), &v1alpha1.VirtualSwitch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualSwitch), err
}

// List takes label and field selectors, and returns the list of VirtualSwitches that match those selectors.
func (c *FakeVirtualSwitches) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.VirtualSwitchList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(virtualswitchesResource, virtualswitchesKind, c.ns, opts), &v1alpha1.VirtualSwitchList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.VirtualSwitchList{ListMeta: obj.(*v1alpha1.VirtualSwitchList).ListMeta}
	for _, item := range obj.(*v1alpha1.VirtualSwitchList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested virtualSwitches.
func (c *FakeVirtualSwitches) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(virtualswitchesResource, c.ns, opts))

}

// Create takes the representation of a virtualSwitch and creates it.  Returns the server's representation of the virtualSwitch, and an error, if there is any.
func (c *FakeVirtualSwitches) Create(ctx context.Context, virtualSwitch *v1alpha1.VirtualSwitch, opts v1.CreateOptions) (result *v1alpha1.VirtualSwitch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(virtualswitchesResource, c.ns, virtualSwitch), &v1alpha1.VirtualSwitch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualSwitch), err
}

// Update takes the representation of a virtualSwitch and updates it. Returns the server's representation of the virtualSwitch, and an error, if there is any.
func (c *FakeVirtualSwitches) Update(ctx context.Context, virtualSwitch *v1alpha1.VirtualSwitch, opts v1.UpdateOptions) (result *v1alpha1.VirtualSwitch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(virtualswitchesResource, c.ns, virtualSwitch), &v1alpha1.VirtualSwitch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualSwitch), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeVirtualSwitches) UpdateStatus(ctx context.Context, virtualSwitch *v1alpha1.VirtualSwitch, opts v1.UpdateOptions) (*v1alpha1.VirtualSwitch, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(virtualswitchesResource, "status", c.ns, virtualSwitch), &v1alpha1.VirtualSwitch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualSwitch), err
}

// Delete takes name of the virtualSwitch and deletes it. Returns an error if one occurs.
func (c *FakeVirtualSwitches) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(virtualswitchesResource, c.ns, name), &v1alpha1.VirtualSwitch{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeVirtualSwitches) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(virtualswitchesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.VirtualSwitchList{})
	return err
}

// Patch applies the patch and returns the patched virtualSwitch.
func (c *FakeVirtualSwitches) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.VirtualSwitch, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(virtualswitchesResource, c.ns, name, pt, data, subresources...), &v1alpha1.VirtualSwitch{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.VirtualSwitch), err
}
