/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterListerExpansion allows custom methods to be added to
// ClusterLister.
type ClusterListerExpansion interface{}

// ClusterNamespaceListerExpansion allows custom methods to be added to
// ClusterNamespaceLister.
type ClusterNamespaceListerExpansion interface{}

// ClusterHostGroupListerExpansion allows custom methods to be added to
// ClusterHostGroupLister.
type ClusterHostGroupListerExpansion interface{}

// ClusterHostGroupNamespaceListerExpansion allows custom methods to be added to
// ClusterHostGroupNamespaceLister.
type ClusterHostGroupNamespaceListerExpansion interface{}

// ClusterVmAffinityRuleListerExpansion allows custom methods to be added to
// ClusterVmAffinityRuleLister.
type ClusterVmAffinityRuleListerExpansion interface{}

// ClusterVmAffinityRuleNamespaceListerExpansion allows custom methods to be added to
// ClusterVmAffinityRuleNamespaceLister.
type ClusterVmAffinityRuleNamespaceListerExpansion interface{}

// ClusterVmAntiAffinityRuleListerExpansion allows custom methods to be added to
// ClusterVmAntiAffinityRuleLister.
type ClusterVmAntiAffinityRuleListerExpansion interface{}

// ClusterVmAntiAffinityRuleNamespaceListerExpansion allows custom methods to be added to
// ClusterVmAntiAffinityRuleNamespaceLister.
type ClusterVmAntiAffinityRuleNamespaceListerExpansion interface{}

// ClusterVmDependencyRuleListerExpansion allows custom methods to be added to
// ClusterVmDependencyRuleLister.
type ClusterVmDependencyRuleListerExpansion interface{}

// ClusterVmDependencyRuleNamespaceListerExpansion allows custom methods to be added to
// ClusterVmDependencyRuleNamespaceLister.
type ClusterVmDependencyRuleNamespaceListerExpansion interface{}

// ClusterVmGroupListerExpansion allows custom methods to be added to
// ClusterVmGroupLister.
type ClusterVmGroupListerExpansion interface{}

// ClusterVmGroupNamespaceListerExpansion allows custom methods to be added to
// ClusterVmGroupNamespaceLister.
type ClusterVmGroupNamespaceListerExpansion interface{}

// ClusterVmHostRuleListerExpansion allows custom methods to be added to
// ClusterVmHostRuleLister.
type ClusterVmHostRuleListerExpansion interface{}

// ClusterVmHostRuleNamespaceListerExpansion allows custom methods to be added to
// ClusterVmHostRuleNamespaceLister.
type ClusterVmHostRuleNamespaceListerExpansion interface{}
