/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DiskListerExpansion allows custom methods to be added to
// DiskLister.
type DiskListerExpansion interface{}

// DiskNamespaceListerExpansion allows custom methods to be added to
// DiskNamespaceLister.
type DiskNamespaceListerExpansion interface{}

// MachineListerExpansion allows custom methods to be added to
// MachineLister.
type MachineListerExpansion interface{}

// MachineNamespaceListerExpansion allows custom methods to be added to
// MachineNamespaceLister.
type MachineNamespaceListerExpansion interface{}

// MachineSnapshotListerExpansion allows custom methods to be added to
// MachineSnapshotLister.
type MachineSnapshotListerExpansion interface{}

// MachineSnapshotNamespaceListerExpansion allows custom methods to be added to
// MachineSnapshotNamespaceLister.
type MachineSnapshotNamespaceListerExpansion interface{}
