/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-vsphere-api/apis/compute/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterVmDependencyRules implements ClusterVmDependencyRuleInterface
type FakeClusterVmDependencyRules struct {
	Fake *FakeComputeV1alpha1
	ns   string
}

var clustervmdependencyrulesResource = schema.GroupVersionResource{Group: "compute.vsphere.kubeform.com", Version: "v1alpha1", Resource: "clustervmdependencyrules"}

var clustervmdependencyrulesKind = schema.GroupVersionKind{Group: "compute.vsphere.kubeform.com", Version: "v1alpha1", Kind: "ClusterVmDependencyRule"}

// Get takes name of the clusterVmDependencyRule, and returns the corresponding clusterVmDependencyRule object, and an error if there is any.
func (c *FakeClusterVmDependencyRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterVmDependencyRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clustervmdependencyrulesResource, c.ns, name), &v1alpha1.ClusterVmDependencyRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterVmDependencyRule), err
}

// List takes label and field selectors, and returns the list of ClusterVmDependencyRules that match those selectors.
func (c *FakeClusterVmDependencyRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterVmDependencyRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clustervmdependencyrulesResource, clustervmdependencyrulesKind, c.ns, opts), &v1alpha1.ClusterVmDependencyRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterVmDependencyRuleList{ListMeta: obj.(*v1alpha1.ClusterVmDependencyRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterVmDependencyRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterVmDependencyRules.
func (c *FakeClusterVmDependencyRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clustervmdependencyrulesResource, c.ns, opts))

}

// Create takes the representation of a clusterVmDependencyRule and creates it.  Returns the server's representation of the clusterVmDependencyRule, and an error, if there is any.
func (c *FakeClusterVmDependencyRules) Create(ctx context.Context, clusterVmDependencyRule *v1alpha1.ClusterVmDependencyRule, opts v1.CreateOptions) (result *v1alpha1.ClusterVmDependencyRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clustervmdependencyrulesResource, c.ns, clusterVmDependencyRule), &v1alpha1.ClusterVmDependencyRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterVmDependencyRule), err
}

// Update takes the representation of a clusterVmDependencyRule and updates it. Returns the server's representation of the clusterVmDependencyRule, and an error, if there is any.
func (c *FakeClusterVmDependencyRules) Update(ctx context.Context, clusterVmDependencyRule *v1alpha1.ClusterVmDependencyRule, opts v1.UpdateOptions) (result *v1alpha1.ClusterVmDependencyRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clustervmdependencyrulesResource, c.ns, clusterVmDependencyRule), &v1alpha1.ClusterVmDependencyRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterVmDependencyRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterVmDependencyRules) UpdateStatus(ctx context.Context, clusterVmDependencyRule *v1alpha1.ClusterVmDependencyRule, opts v1.UpdateOptions) (*v1alpha1.ClusterVmDependencyRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clustervmdependencyrulesResource, "status", c.ns, clusterVmDependencyRule), &v1alpha1.ClusterVmDependencyRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterVmDependencyRule), err
}

// Delete takes name of the clusterVmDependencyRule and deletes it. Returns an error if one occurs.
func (c *FakeClusterVmDependencyRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clustervmdependencyrulesResource, c.ns, name), &v1alpha1.ClusterVmDependencyRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterVmDependencyRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clustervmdependencyrulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterVmDependencyRuleList{})
	return err
}

// Patch applies the patch and returns the patched clusterVmDependencyRule.
func (c *FakeClusterVmDependencyRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterVmDependencyRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clustervmdependencyrulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ClusterVmDependencyRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterVmDependencyRule), err
}
