/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-vsphere-api/apis/compute/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterVmHostRules implements ClusterVmHostRuleInterface
type FakeClusterVmHostRules struct {
	Fake *FakeComputeV1alpha1
	ns   string
}

var clustervmhostrulesResource = schema.GroupVersionResource{Group: "compute.vsphere.kubeform.com", Version: "v1alpha1", Resource: "clustervmhostrules"}

var clustervmhostrulesKind = schema.GroupVersionKind{Group: "compute.vsphere.kubeform.com", Version: "v1alpha1", Kind: "ClusterVmHostRule"}

// Get takes name of the clusterVmHostRule, and returns the corresponding clusterVmHostRule object, and an error if there is any.
func (c *FakeClusterVmHostRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterVmHostRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clustervmhostrulesResource, c.ns, name), &v1alpha1.ClusterVmHostRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterVmHostRule), err
}

// List takes label and field selectors, and returns the list of ClusterVmHostRules that match those selectors.
func (c *FakeClusterVmHostRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterVmHostRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clustervmhostrulesResource, clustervmhostrulesKind, c.ns, opts), &v1alpha1.ClusterVmHostRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterVmHostRuleList{ListMeta: obj.(*v1alpha1.ClusterVmHostRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterVmHostRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterVmHostRules.
func (c *FakeClusterVmHostRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clustervmhostrulesResource, c.ns, opts))

}

// Create takes the representation of a clusterVmHostRule and creates it.  Returns the server's representation of the clusterVmHostRule, and an error, if there is any.
func (c *FakeClusterVmHostRules) Create(ctx context.Context, clusterVmHostRule *v1alpha1.ClusterVmHostRule, opts v1.CreateOptions) (result *v1alpha1.ClusterVmHostRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clustervmhostrulesResource, c.ns, clusterVmHostRule), &v1alpha1.ClusterVmHostRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterVmHostRule), err
}

// Update takes the representation of a clusterVmHostRule and updates it. Returns the server's representation of the clusterVmHostRule, and an error, if there is any.
func (c *FakeClusterVmHostRules) Update(ctx context.Context, clusterVmHostRule *v1alpha1.ClusterVmHostRule, opts v1.UpdateOptions) (result *v1alpha1.ClusterVmHostRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clustervmhostrulesResource, c.ns, clusterVmHostRule), &v1alpha1.ClusterVmHostRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterVmHostRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterVmHostRules) UpdateStatus(ctx context.Context, clusterVmHostRule *v1alpha1.ClusterVmHostRule, opts v1.UpdateOptions) (*v1alpha1.ClusterVmHostRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clustervmhostrulesResource, "status", c.ns, clusterVmHostRule), &v1alpha1.ClusterVmHostRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterVmHostRule), err
}

// Delete takes name of the clusterVmHostRule and deletes it. Returns an error if one occurs.
func (c *FakeClusterVmHostRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clustervmhostrulesResource, c.ns, name), &v1alpha1.ClusterVmHostRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterVmHostRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clustervmhostrulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterVmHostRuleList{})
	return err
}

// Patch applies the patch and returns the patched clusterVmHostRule.
func (c *FakeClusterVmHostRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterVmHostRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clustervmhostrulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ClusterVmHostRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterVmHostRule), err
}
