/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-vsphere-api/apis/compute/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterHostGroups implements ClusterHostGroupInterface
type FakeClusterHostGroups struct {
	Fake *FakeComputeV1alpha1
	ns   string
}

var clusterhostgroupsResource = schema.GroupVersionResource{Group: "compute.vsphere.kubeform.com", Version: "v1alpha1", Resource: "clusterhostgroups"}

var clusterhostgroupsKind = schema.GroupVersionKind{Group: "compute.vsphere.kubeform.com", Version: "v1alpha1", Kind: "ClusterHostGroup"}

// Get takes name of the clusterHostGroup, and returns the corresponding clusterHostGroup object, and an error if there is any.
func (c *FakeClusterHostGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterHostGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clusterhostgroupsResource, c.ns, name), &v1alpha1.ClusterHostGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterHostGroup), err
}

// List takes label and field selectors, and returns the list of ClusterHostGroups that match those selectors.
func (c *FakeClusterHostGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterHostGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clusterhostgroupsResource, clusterhostgroupsKind, c.ns, opts), &v1alpha1.ClusterHostGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterHostGroupList{ListMeta: obj.(*v1alpha1.ClusterHostGroupList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterHostGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterHostGroups.
func (c *FakeClusterHostGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clusterhostgroupsResource, c.ns, opts))

}

// Create takes the representation of a clusterHostGroup and creates it.  Returns the server's representation of the clusterHostGroup, and an error, if there is any.
func (c *FakeClusterHostGroups) Create(ctx context.Context, clusterHostGroup *v1alpha1.ClusterHostGroup, opts v1.CreateOptions) (result *v1alpha1.ClusterHostGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clusterhostgroupsResource, c.ns, clusterHostGroup), &v1alpha1.ClusterHostGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterHostGroup), err
}

// Update takes the representation of a clusterHostGroup and updates it. Returns the server's representation of the clusterHostGroup, and an error, if there is any.
func (c *FakeClusterHostGroups) Update(ctx context.Context, clusterHostGroup *v1alpha1.ClusterHostGroup, opts v1.UpdateOptions) (result *v1alpha1.ClusterHostGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clusterhostgroupsResource, c.ns, clusterHostGroup), &v1alpha1.ClusterHostGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterHostGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterHostGroups) UpdateStatus(ctx context.Context, clusterHostGroup *v1alpha1.ClusterHostGroup, opts v1.UpdateOptions) (*v1alpha1.ClusterHostGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clusterhostgroupsResource, "status", c.ns, clusterHostGroup), &v1alpha1.ClusterHostGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterHostGroup), err
}

// Delete takes name of the clusterHostGroup and deletes it. Returns an error if one occurs.
func (c *FakeClusterHostGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clusterhostgroupsResource, c.ns, name), &v1alpha1.ClusterHostGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterHostGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clusterhostgroupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterHostGroupList{})
	return err
}

// Patch applies the patch and returns the patched clusterHostGroup.
func (c *FakeClusterHostGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterHostGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clusterhostgroupsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ClusterHostGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterHostGroup), err
}
