/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-vsphere-api/apis/compute/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterVmAntiAffinityRules implements ClusterVmAntiAffinityRuleInterface
type FakeClusterVmAntiAffinityRules struct {
	Fake *FakeComputeV1alpha1
	ns   string
}

var clustervmantiaffinityrulesResource = schema.GroupVersionResource{Group: "compute.vsphere.kubeform.com", Version: "v1alpha1", Resource: "clustervmantiaffinityrules"}

var clustervmantiaffinityrulesKind = schema.GroupVersionKind{Group: "compute.vsphere.kubeform.com", Version: "v1alpha1", Kind: "ClusterVmAntiAffinityRule"}

// Get takes name of the clusterVmAntiAffinityRule, and returns the corresponding clusterVmAntiAffinityRule object, and an error if there is any.
func (c *FakeClusterVmAntiAffinityRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterVmAntiAffinityRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clustervmantiaffinityrulesResource, c.ns, name), &v1alpha1.ClusterVmAntiAffinityRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterVmAntiAffinityRule), err
}

// List takes label and field selectors, and returns the list of ClusterVmAntiAffinityRules that match those selectors.
func (c *FakeClusterVmAntiAffinityRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterVmAntiAffinityRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clustervmantiaffinityrulesResource, clustervmantiaffinityrulesKind, c.ns, opts), &v1alpha1.ClusterVmAntiAffinityRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterVmAntiAffinityRuleList{ListMeta: obj.(*v1alpha1.ClusterVmAntiAffinityRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterVmAntiAffinityRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterVmAntiAffinityRules.
func (c *FakeClusterVmAntiAffinityRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clustervmantiaffinityrulesResource, c.ns, opts))

}

// Create takes the representation of a clusterVmAntiAffinityRule and creates it.  Returns the server's representation of the clusterVmAntiAffinityRule, and an error, if there is any.
func (c *FakeClusterVmAntiAffinityRules) Create(ctx context.Context, clusterVmAntiAffinityRule *v1alpha1.ClusterVmAntiAffinityRule, opts v1.CreateOptions) (result *v1alpha1.ClusterVmAntiAffinityRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clustervmantiaffinityrulesResource, c.ns, clusterVmAntiAffinityRule), &v1alpha1.ClusterVmAntiAffinityRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterVmAntiAffinityRule), err
}

// Update takes the representation of a clusterVmAntiAffinityRule and updates it. Returns the server's representation of the clusterVmAntiAffinityRule, and an error, if there is any.
func (c *FakeClusterVmAntiAffinityRules) Update(ctx context.Context, clusterVmAntiAffinityRule *v1alpha1.ClusterVmAntiAffinityRule, opts v1.UpdateOptions) (result *v1alpha1.ClusterVmAntiAffinityRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clustervmantiaffinityrulesResource, c.ns, clusterVmAntiAffinityRule), &v1alpha1.ClusterVmAntiAffinityRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterVmAntiAffinityRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeClusterVmAntiAffinityRules) UpdateStatus(ctx context.Context, clusterVmAntiAffinityRule *v1alpha1.ClusterVmAntiAffinityRule, opts v1.UpdateOptions) (*v1alpha1.ClusterVmAntiAffinityRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(clustervmantiaffinityrulesResource, "status", c.ns, clusterVmAntiAffinityRule), &v1alpha1.ClusterVmAntiAffinityRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterVmAntiAffinityRule), err
}

// Delete takes name of the clusterVmAntiAffinityRule and deletes it. Returns an error if one occurs.
func (c *FakeClusterVmAntiAffinityRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(clustervmantiaffinityrulesResource, c.ns, name), &v1alpha1.ClusterVmAntiAffinityRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterVmAntiAffinityRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clustervmantiaffinityrulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterVmAntiAffinityRuleList{})
	return err
}

// Patch applies the patch and returns the patched clusterVmAntiAffinityRule.
func (c *FakeClusterVmAntiAffinityRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterVmAntiAffinityRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clustervmantiaffinityrulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ClusterVmAntiAffinityRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterVmAntiAffinityRule), err
}
