/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	reflect "reflect"
	sync "sync"
	time "time"

	versioned "kubeform.dev/provider-vsphere-api/client/clientset/versioned"
	compute "kubeform.dev/provider-vsphere-api/client/informers/externalversions/compute"
	content "kubeform.dev/provider-vsphere-api/client/informers/externalversions/content"
	custom "kubeform.dev/provider-vsphere-api/client/informers/externalversions/custom"
	datacenter "kubeform.dev/provider-vsphere-api/client/informers/externalversions/datacenter"
	datastore "kubeform.dev/provider-vsphere-api/client/informers/externalversions/datastore"
	distributed "kubeform.dev/provider-vsphere-api/client/informers/externalversions/distributed"
	dpm "kubeform.dev/provider-vsphere-api/client/informers/externalversions/dpm"
	drs "kubeform.dev/provider-vsphere-api/client/informers/externalversions/drs"
	entity "kubeform.dev/provider-vsphere-api/client/informers/externalversions/entity"
	file "kubeform.dev/provider-vsphere-api/client/informers/externalversions/file"
	folder "kubeform.dev/provider-vsphere-api/client/informers/externalversions/folder"
	ha "kubeform.dev/provider-vsphere-api/client/informers/externalversions/ha"
	host "kubeform.dev/provider-vsphere-api/client/informers/externalversions/host"
	internalinterfaces "kubeform.dev/provider-vsphere-api/client/informers/externalversions/internalinterfaces"
	license "kubeform.dev/provider-vsphere-api/client/informers/externalversions/license"
	nas "kubeform.dev/provider-vsphere-api/client/informers/externalversions/nas"
	resource "kubeform.dev/provider-vsphere-api/client/informers/externalversions/resource"
	role "kubeform.dev/provider-vsphere-api/client/informers/externalversions/role"
	storage "kubeform.dev/provider-vsphere-api/client/informers/externalversions/storage"
	tag "kubeform.dev/provider-vsphere-api/client/informers/externalversions/tag"
	vapp "kubeform.dev/provider-vsphere-api/client/informers/externalversions/vapp"
	virtual "kubeform.dev/provider-vsphere-api/client/informers/externalversions/virtual"
	vm "kubeform.dev/provider-vsphere-api/client/informers/externalversions/vm"
	vmfs "kubeform.dev/provider-vsphere-api/client/informers/externalversions/vmfs"
	vnic "kubeform.dev/provider-vsphere-api/client/informers/externalversions/vnic"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// SharedInformerOption defines the functional option type for SharedInformerFactory.
type SharedInformerOption func(*sharedInformerFactory) *sharedInformerFactory

type sharedInformerFactory struct {
	client           versioned.Interface
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	lock             sync.Mutex
	defaultResync    time.Duration
	customResync     map[reflect.Type]time.Duration

	informers map[reflect.Type]cache.SharedIndexInformer
	// startedInformers is used for tracking which informers have been started.
	// This allows Start() to be called multiple times safely.
	startedInformers map[reflect.Type]bool
}

// WithCustomResyncConfig sets a custom resync period for the specified informer types.
func WithCustomResyncConfig(resyncConfig map[v1.Object]time.Duration) SharedInformerOption {
	return func(factory *sharedInformerFactory) *sharedInformerFactory {
		for k, v := range resyncConfig {
			factory.customResync[reflect.TypeOf(k)] = v
		}
		return factory
	}
}

// WithTweakListOptions sets a custom filter on all listers of the configured SharedInformerFactory.
func WithTweakListOptions(tweakListOptions internalinterfaces.TweakListOptionsFunc) SharedInformerOption {
	return func(factory *sharedInformerFactory) *sharedInformerFactory {
		factory.tweakListOptions = tweakListOptions
		return factory
	}
}

// WithNamespace limits the SharedInformerFactory to the specified namespace.
func WithNamespace(namespace string) SharedInformerOption {
	return func(factory *sharedInformerFactory) *sharedInformerFactory {
		factory.namespace = namespace
		return factory
	}
}

// NewSharedInformerFactory constructs a new instance of sharedInformerFactory for all namespaces.
func NewSharedInformerFactory(client versioned.Interface, defaultResync time.Duration) SharedInformerFactory {
	return NewSharedInformerFactoryWithOptions(client, defaultResync)
}

// NewFilteredSharedInformerFactory constructs a new instance of sharedInformerFactory.
// Listers obtained via this SharedInformerFactory will be subject to the same filters
// as specified here.
// Deprecated: Please use NewSharedInformerFactoryWithOptions instead
func NewFilteredSharedInformerFactory(client versioned.Interface, defaultResync time.Duration, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) SharedInformerFactory {
	return NewSharedInformerFactoryWithOptions(client, defaultResync, WithNamespace(namespace), WithTweakListOptions(tweakListOptions))
}

// NewSharedInformerFactoryWithOptions constructs a new instance of a SharedInformerFactory with additional options.
func NewSharedInformerFactoryWithOptions(client versioned.Interface, defaultResync time.Duration, options ...SharedInformerOption) SharedInformerFactory {
	factory := &sharedInformerFactory{
		client:           client,
		namespace:        v1.NamespaceAll,
		defaultResync:    defaultResync,
		informers:        make(map[reflect.Type]cache.SharedIndexInformer),
		startedInformers: make(map[reflect.Type]bool),
		customResync:     make(map[reflect.Type]time.Duration),
	}

	// Apply all options
	for _, opt := range options {
		factory = opt(factory)
	}

	return factory
}

// Start initializes all requested informers.
func (f *sharedInformerFactory) Start(stopCh <-chan struct{}) {
	f.lock.Lock()
	defer f.lock.Unlock()

	for informerType, informer := range f.informers {
		if !f.startedInformers[informerType] {
			go informer.Run(stopCh)
			f.startedInformers[informerType] = true
		}
	}
}

// WaitForCacheSync waits for all started informers' cache were synced.
func (f *sharedInformerFactory) WaitForCacheSync(stopCh <-chan struct{}) map[reflect.Type]bool {
	informers := func() map[reflect.Type]cache.SharedIndexInformer {
		f.lock.Lock()
		defer f.lock.Unlock()

		informers := map[reflect.Type]cache.SharedIndexInformer{}
		for informerType, informer := range f.informers {
			if f.startedInformers[informerType] {
				informers[informerType] = informer
			}
		}
		return informers
	}()

	res := map[reflect.Type]bool{}
	for informType, informer := range informers {
		res[informType] = cache.WaitForCacheSync(stopCh, informer.HasSynced)
	}
	return res
}

// InternalInformerFor returns the SharedIndexInformer for obj using an internal
// client.
func (f *sharedInformerFactory) InformerFor(obj runtime.Object, newFunc internalinterfaces.NewInformerFunc) cache.SharedIndexInformer {
	f.lock.Lock()
	defer f.lock.Unlock()

	informerType := reflect.TypeOf(obj)
	informer, exists := f.informers[informerType]
	if exists {
		return informer
	}

	resyncPeriod, exists := f.customResync[informerType]
	if !exists {
		resyncPeriod = f.defaultResync
	}

	informer = newFunc(f.client, resyncPeriod)
	f.informers[informerType] = informer

	return informer
}

// SharedInformerFactory provides shared informers for resources in all known
// API group versions.
type SharedInformerFactory interface {
	internalinterfaces.SharedInformerFactory
	ForResource(resource schema.GroupVersionResource) (GenericInformer, error)
	WaitForCacheSync(stopCh <-chan struct{}) map[reflect.Type]bool

	Compute() compute.Interface
	Content() content.Interface
	Custom() custom.Interface
	Datacenter() datacenter.Interface
	Datastore() datastore.Interface
	Distributed() distributed.Interface
	Dpm() dpm.Interface
	Drs() drs.Interface
	Entity() entity.Interface
	File() file.Interface
	Folder() folder.Interface
	Ha() ha.Interface
	Host() host.Interface
	License() license.Interface
	Nas() nas.Interface
	Resource() resource.Interface
	Role() role.Interface
	Storage() storage.Interface
	Tag() tag.Interface
	Vapp() vapp.Interface
	Virtual() virtual.Interface
	Vm() vm.Interface
	Vmfs() vmfs.Interface
	Vnic() vnic.Interface
}

func (f *sharedInformerFactory) Compute() compute.Interface {
	return compute.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Content() content.Interface {
	return content.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Custom() custom.Interface {
	return custom.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Datacenter() datacenter.Interface {
	return datacenter.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Datastore() datastore.Interface {
	return datastore.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Distributed() distributed.Interface {
	return distributed.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Dpm() dpm.Interface {
	return dpm.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Drs() drs.Interface {
	return drs.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Entity() entity.Interface {
	return entity.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) File() file.Interface {
	return file.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Folder() folder.Interface {
	return folder.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Ha() ha.Interface {
	return ha.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Host() host.Interface {
	return host.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) License() license.Interface {
	return license.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Nas() nas.Interface {
	return nas.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Resource() resource.Interface {
	return resource.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Role() role.Interface {
	return role.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Storage() storage.Interface {
	return storage.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Tag() tag.Interface {
	return tag.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Vapp() vapp.Interface {
	return vapp.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Virtual() virtual.Interface {
	return virtual.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Vm() vm.Interface {
	return vm.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Vmfs() vmfs.Interface {
	return vmfs.New(f, f.namespace, f.tweakListOptions)
}

func (f *sharedInformerFactory) Vnic() vnic.Interface {
	return vnic.New(f, f.namespace, f.tweakListOptions)
}
