/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package externalversions

import (
	"fmt"

	v1alpha1 "kubeform.dev/provider-vsphere-api/apis/compute/v1alpha1"
	contentv1alpha1 "kubeform.dev/provider-vsphere-api/apis/content/v1alpha1"
	customv1alpha1 "kubeform.dev/provider-vsphere-api/apis/custom/v1alpha1"
	datacenterv1alpha1 "kubeform.dev/provider-vsphere-api/apis/datacenter/v1alpha1"
	datastorev1alpha1 "kubeform.dev/provider-vsphere-api/apis/datastore/v1alpha1"
	distributedv1alpha1 "kubeform.dev/provider-vsphere-api/apis/distributed/v1alpha1"
	dpmv1alpha1 "kubeform.dev/provider-vsphere-api/apis/dpm/v1alpha1"
	drsv1alpha1 "kubeform.dev/provider-vsphere-api/apis/drs/v1alpha1"
	entityv1alpha1 "kubeform.dev/provider-vsphere-api/apis/entity/v1alpha1"
	filev1alpha1 "kubeform.dev/provider-vsphere-api/apis/file/v1alpha1"
	folderv1alpha1 "kubeform.dev/provider-vsphere-api/apis/folder/v1alpha1"
	hav1alpha1 "kubeform.dev/provider-vsphere-api/apis/ha/v1alpha1"
	hostv1alpha1 "kubeform.dev/provider-vsphere-api/apis/host/v1alpha1"
	licensev1alpha1 "kubeform.dev/provider-vsphere-api/apis/license/v1alpha1"
	nasv1alpha1 "kubeform.dev/provider-vsphere-api/apis/nas/v1alpha1"
	resourcev1alpha1 "kubeform.dev/provider-vsphere-api/apis/resource/v1alpha1"
	rolev1alpha1 "kubeform.dev/provider-vsphere-api/apis/role/v1alpha1"
	storagev1alpha1 "kubeform.dev/provider-vsphere-api/apis/storage/v1alpha1"
	tagv1alpha1 "kubeform.dev/provider-vsphere-api/apis/tag/v1alpha1"
	vappv1alpha1 "kubeform.dev/provider-vsphere-api/apis/vapp/v1alpha1"
	virtualv1alpha1 "kubeform.dev/provider-vsphere-api/apis/virtual/v1alpha1"
	vmv1alpha1 "kubeform.dev/provider-vsphere-api/apis/vm/v1alpha1"
	vmfsv1alpha1 "kubeform.dev/provider-vsphere-api/apis/vmfs/v1alpha1"
	vnicv1alpha1 "kubeform.dev/provider-vsphere-api/apis/vnic/v1alpha1"

	schema "k8s.io/apimachinery/pkg/runtime/schema"
	cache "k8s.io/client-go/tools/cache"
)

// GenericInformer is type of SharedIndexInformer which will locate and delegate to other
// sharedInformers based on type
type GenericInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() cache.GenericLister
}

type genericInformer struct {
	informer cache.SharedIndexInformer
	resource schema.GroupResource
}

// Informer returns the SharedIndexInformer.
func (f *genericInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

// Lister returns the GenericLister.
func (f *genericInformer) Lister() cache.GenericLister {
	return cache.NewGenericLister(f.Informer().GetIndexer(), f.resource)
}

// ForResource gives generic access to a shared informer of the matching type
// TODO extend this to unknown resources with a client pool
func (f *sharedInformerFactory) ForResource(resource schema.GroupVersionResource) (GenericInformer, error) {
	switch resource {
	// Group=compute.vsphere.kubeform.com, Version=v1alpha1
	case v1alpha1.SchemeGroupVersion.WithResource("clusters"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Compute().V1alpha1().Clusters().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("clusterhostgroups"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Compute().V1alpha1().ClusterHostGroups().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("clustervmaffinityrules"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Compute().V1alpha1().ClusterVmAffinityRules().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("clustervmantiaffinityrules"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Compute().V1alpha1().ClusterVmAntiAffinityRules().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("clustervmdependencyrules"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Compute().V1alpha1().ClusterVmDependencyRules().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("clustervmgroups"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Compute().V1alpha1().ClusterVmGroups().Informer()}, nil
	case v1alpha1.SchemeGroupVersion.WithResource("clustervmhostrules"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Compute().V1alpha1().ClusterVmHostRules().Informer()}, nil

		// Group=content.vsphere.kubeform.com, Version=v1alpha1
	case contentv1alpha1.SchemeGroupVersion.WithResource("libraries"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Content().V1alpha1().Libraries().Informer()}, nil
	case contentv1alpha1.SchemeGroupVersion.WithResource("libraryitems"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Content().V1alpha1().LibraryItems().Informer()}, nil

		// Group=custom.vsphere.kubeform.com, Version=v1alpha1
	case customv1alpha1.SchemeGroupVersion.WithResource("attributes"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Custom().V1alpha1().Attributes().Informer()}, nil

		// Group=datacenter.vsphere.kubeform.com, Version=v1alpha1
	case datacenterv1alpha1.SchemeGroupVersion.WithResource("datacenters"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Datacenter().V1alpha1().Datacenters().Informer()}, nil

		// Group=datastore.vsphere.kubeform.com, Version=v1alpha1
	case datastorev1alpha1.SchemeGroupVersion.WithResource("clusters"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Datastore().V1alpha1().Clusters().Informer()}, nil
	case datastorev1alpha1.SchemeGroupVersion.WithResource("clustervmantiaffinityrules"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Datastore().V1alpha1().ClusterVmAntiAffinityRules().Informer()}, nil

		// Group=distributed.vsphere.kubeform.com, Version=v1alpha1
	case distributedv1alpha1.SchemeGroupVersion.WithResource("portgroups"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Distributed().V1alpha1().PortGroups().Informer()}, nil
	case distributedv1alpha1.SchemeGroupVersion.WithResource("virtualswitches"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Distributed().V1alpha1().VirtualSwitches().Informer()}, nil

		// Group=dpm.vsphere.kubeform.com, Version=v1alpha1
	case dpmv1alpha1.SchemeGroupVersion.WithResource("hostoverrides"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Dpm().V1alpha1().HostOverrides().Informer()}, nil

		// Group=drs.vsphere.kubeform.com, Version=v1alpha1
	case drsv1alpha1.SchemeGroupVersion.WithResource("vmoverrides"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Drs().V1alpha1().VmOverrides().Informer()}, nil

		// Group=entity.vsphere.kubeform.com, Version=v1alpha1
	case entityv1alpha1.SchemeGroupVersion.WithResource("permissionses"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Entity().V1alpha1().Permissionses().Informer()}, nil

		// Group=file.vsphere.kubeform.com, Version=v1alpha1
	case filev1alpha1.SchemeGroupVersion.WithResource("files"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.File().V1alpha1().Files().Informer()}, nil

		// Group=folder.vsphere.kubeform.com, Version=v1alpha1
	case folderv1alpha1.SchemeGroupVersion.WithResource("folders"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Folder().V1alpha1().Folders().Informer()}, nil

		// Group=ha.vsphere.kubeform.com, Version=v1alpha1
	case hav1alpha1.SchemeGroupVersion.WithResource("vmoverrides"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Ha().V1alpha1().VmOverrides().Informer()}, nil

		// Group=host.vsphere.kubeform.com, Version=v1alpha1
	case hostv1alpha1.SchemeGroupVersion.WithResource("hosts"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Host().V1alpha1().Hosts().Informer()}, nil
	case hostv1alpha1.SchemeGroupVersion.WithResource("portgroups"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Host().V1alpha1().PortGroups().Informer()}, nil
	case hostv1alpha1.SchemeGroupVersion.WithResource("virtualswitches"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Host().V1alpha1().VirtualSwitches().Informer()}, nil

		// Group=license.vsphere.kubeform.com, Version=v1alpha1
	case licensev1alpha1.SchemeGroupVersion.WithResource("licenses"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.License().V1alpha1().Licenses().Informer()}, nil

		// Group=nas.vsphere.kubeform.com, Version=v1alpha1
	case nasv1alpha1.SchemeGroupVersion.WithResource("datastores"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Nas().V1alpha1().Datastores().Informer()}, nil

		// Group=resource.vsphere.kubeform.com, Version=v1alpha1
	case resourcev1alpha1.SchemeGroupVersion.WithResource("pools"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Resource().V1alpha1().Pools().Informer()}, nil

		// Group=role.vsphere.kubeform.com, Version=v1alpha1
	case rolev1alpha1.SchemeGroupVersion.WithResource("roles"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Role().V1alpha1().Roles().Informer()}, nil

		// Group=storage.vsphere.kubeform.com, Version=v1alpha1
	case storagev1alpha1.SchemeGroupVersion.WithResource("drsvmoverrides"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Storage().V1alpha1().DrsVmOverrides().Informer()}, nil

		// Group=tag.vsphere.kubeform.com, Version=v1alpha1
	case tagv1alpha1.SchemeGroupVersion.WithResource("categories"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Tag().V1alpha1().Categories().Informer()}, nil
	case tagv1alpha1.SchemeGroupVersion.WithResource("tags"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Tag().V1alpha1().Tags().Informer()}, nil

		// Group=vapp.vsphere.kubeform.com, Version=v1alpha1
	case vappv1alpha1.SchemeGroupVersion.WithResource("containers"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Vapp().V1alpha1().Containers().Informer()}, nil
	case vappv1alpha1.SchemeGroupVersion.WithResource("entities"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Vapp().V1alpha1().Entities().Informer()}, nil

		// Group=virtual.vsphere.kubeform.com, Version=v1alpha1
	case virtualv1alpha1.SchemeGroupVersion.WithResource("disks"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Virtual().V1alpha1().Disks().Informer()}, nil
	case virtualv1alpha1.SchemeGroupVersion.WithResource("machines"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Virtual().V1alpha1().Machines().Informer()}, nil
	case virtualv1alpha1.SchemeGroupVersion.WithResource("machinesnapshots"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Virtual().V1alpha1().MachineSnapshots().Informer()}, nil

		// Group=vm.vsphere.kubeform.com, Version=v1alpha1
	case vmv1alpha1.SchemeGroupVersion.WithResource("storagepolicies"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Vm().V1alpha1().StoragePolicies().Informer()}, nil

		// Group=vmfs.vsphere.kubeform.com, Version=v1alpha1
	case vmfsv1alpha1.SchemeGroupVersion.WithResource("datastores"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Vmfs().V1alpha1().Datastores().Informer()}, nil

		// Group=vnic.vsphere.kubeform.com, Version=v1alpha1
	case vnicv1alpha1.SchemeGroupVersion.WithResource("vnics"):
		return &genericInformer{resource: resource.GroupResource(), informer: f.Vnic().V1alpha1().Vnics().Informer()}, nil

	}

	return nil, fmt.Errorf("no informer found for %v", resource)
}
