/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-vsphere-api/apis/compute/v1alpha1"
	scheme "kubeform.dev/provider-vsphere-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterVmAntiAffinityRulesGetter has a method to return a ClusterVmAntiAffinityRuleInterface.
// A group's client should implement this interface.
type ClusterVmAntiAffinityRulesGetter interface {
	ClusterVmAntiAffinityRules(namespace string) ClusterVmAntiAffinityRuleInterface
}

// ClusterVmAntiAffinityRuleInterface has methods to work with ClusterVmAntiAffinityRule resources.
type ClusterVmAntiAffinityRuleInterface interface {
	Create(ctx context.Context, clusterVmAntiAffinityRule *v1alpha1.ClusterVmAntiAffinityRule, opts v1.CreateOptions) (*v1alpha1.ClusterVmAntiAffinityRule, error)
	Update(ctx context.Context, clusterVmAntiAffinityRule *v1alpha1.ClusterVmAntiAffinityRule, opts v1.UpdateOptions) (*v1alpha1.ClusterVmAntiAffinityRule, error)
	UpdateStatus(ctx context.Context, clusterVmAntiAffinityRule *v1alpha1.ClusterVmAntiAffinityRule, opts v1.UpdateOptions) (*v1alpha1.ClusterVmAntiAffinityRule, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterVmAntiAffinityRule, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterVmAntiAffinityRuleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterVmAntiAffinityRule, err error)
	ClusterVmAntiAffinityRuleExpansion
}

// clusterVmAntiAffinityRules implements ClusterVmAntiAffinityRuleInterface
type clusterVmAntiAffinityRules struct {
	client rest.Interface
	ns     string
}

// newClusterVmAntiAffinityRules returns a ClusterVmAntiAffinityRules
func newClusterVmAntiAffinityRules(c *ComputeV1alpha1Client, namespace string) *clusterVmAntiAffinityRules {
	return &clusterVmAntiAffinityRules{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterVmAntiAffinityRule, and returns the corresponding clusterVmAntiAffinityRule object, and an error if there is any.
func (c *clusterVmAntiAffinityRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterVmAntiAffinityRule, err error) {
	result = &v1alpha1.ClusterVmAntiAffinityRule{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clustervmantiaffinityrules").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterVmAntiAffinityRules that match those selectors.
func (c *clusterVmAntiAffinityRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterVmAntiAffinityRuleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterVmAntiAffinityRuleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clustervmantiaffinityrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterVmAntiAffinityRules.
func (c *clusterVmAntiAffinityRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clustervmantiaffinityrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterVmAntiAffinityRule and creates it.  Returns the server's representation of the clusterVmAntiAffinityRule, and an error, if there is any.
func (c *clusterVmAntiAffinityRules) Create(ctx context.Context, clusterVmAntiAffinityRule *v1alpha1.ClusterVmAntiAffinityRule, opts v1.CreateOptions) (result *v1alpha1.ClusterVmAntiAffinityRule, err error) {
	result = &v1alpha1.ClusterVmAntiAffinityRule{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clustervmantiaffinityrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterVmAntiAffinityRule).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterVmAntiAffinityRule and updates it. Returns the server's representation of the clusterVmAntiAffinityRule, and an error, if there is any.
func (c *clusterVmAntiAffinityRules) Update(ctx context.Context, clusterVmAntiAffinityRule *v1alpha1.ClusterVmAntiAffinityRule, opts v1.UpdateOptions) (result *v1alpha1.ClusterVmAntiAffinityRule, err error) {
	result = &v1alpha1.ClusterVmAntiAffinityRule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clustervmantiaffinityrules").
		Name(clusterVmAntiAffinityRule.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterVmAntiAffinityRule).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterVmAntiAffinityRules) UpdateStatus(ctx context.Context, clusterVmAntiAffinityRule *v1alpha1.ClusterVmAntiAffinityRule, opts v1.UpdateOptions) (result *v1alpha1.ClusterVmAntiAffinityRule, err error) {
	result = &v1alpha1.ClusterVmAntiAffinityRule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clustervmantiaffinityrules").
		Name(clusterVmAntiAffinityRule.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterVmAntiAffinityRule).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterVmAntiAffinityRule and deletes it. Returns an error if one occurs.
func (c *clusterVmAntiAffinityRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clustervmantiaffinityrules").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterVmAntiAffinityRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clustervmantiaffinityrules").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterVmAntiAffinityRule.
func (c *clusterVmAntiAffinityRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterVmAntiAffinityRule, err error) {
	result = &v1alpha1.ClusterVmAntiAffinityRule{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clustervmantiaffinityrules").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
