/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-vsphere-api/apis/virtual/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMachineSnapshots implements MachineSnapshotInterface
type FakeMachineSnapshots struct {
	Fake *FakeVirtualV1alpha1
	ns   string
}

var machinesnapshotsResource = schema.GroupVersionResource{Group: "virtual.vsphere.kubeform.com", Version: "v1alpha1", Resource: "machinesnapshots"}

var machinesnapshotsKind = schema.GroupVersionKind{Group: "virtual.vsphere.kubeform.com", Version: "v1alpha1", Kind: "MachineSnapshot"}

// Get takes name of the machineSnapshot, and returns the corresponding machineSnapshot object, and an error if there is any.
func (c *FakeMachineSnapshots) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MachineSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(machinesnapshotsResource, c.ns, name), &v1alpha1.MachineSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineSnapshot), err
}

// List takes label and field selectors, and returns the list of MachineSnapshots that match those selectors.
func (c *FakeMachineSnapshots) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MachineSnapshotList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(machinesnapshotsResource, machinesnapshotsKind, c.ns, opts), &v1alpha1.MachineSnapshotList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MachineSnapshotList{ListMeta: obj.(*v1alpha1.MachineSnapshotList).ListMeta}
	for _, item := range obj.(*v1alpha1.MachineSnapshotList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested machineSnapshots.
func (c *FakeMachineSnapshots) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(machinesnapshotsResource, c.ns, opts))

}

// Create takes the representation of a machineSnapshot and creates it.  Returns the server's representation of the machineSnapshot, and an error, if there is any.
func (c *FakeMachineSnapshots) Create(ctx context.Context, machineSnapshot *v1alpha1.MachineSnapshot, opts v1.CreateOptions) (result *v1alpha1.MachineSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(machinesnapshotsResource, c.ns, machineSnapshot), &v1alpha1.MachineSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineSnapshot), err
}

// Update takes the representation of a machineSnapshot and updates it. Returns the server's representation of the machineSnapshot, and an error, if there is any.
func (c *FakeMachineSnapshots) Update(ctx context.Context, machineSnapshot *v1alpha1.MachineSnapshot, opts v1.UpdateOptions) (result *v1alpha1.MachineSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(machinesnapshotsResource, c.ns, machineSnapshot), &v1alpha1.MachineSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineSnapshot), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMachineSnapshots) UpdateStatus(ctx context.Context, machineSnapshot *v1alpha1.MachineSnapshot, opts v1.UpdateOptions) (*v1alpha1.MachineSnapshot, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(machinesnapshotsResource, "status", c.ns, machineSnapshot), &v1alpha1.MachineSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineSnapshot), err
}

// Delete takes name of the machineSnapshot and deletes it. Returns an error if one occurs.
func (c *FakeMachineSnapshots) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(machinesnapshotsResource, c.ns, name), &v1alpha1.MachineSnapshot{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMachineSnapshots) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(machinesnapshotsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MachineSnapshotList{})
	return err
}

// Patch applies the patch and returns the patched machineSnapshot.
func (c *FakeMachineSnapshots) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MachineSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(machinesnapshotsResource, c.ns, name, pt, data, subresources...), &v1alpha1.MachineSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineSnapshot), err
}
