/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-vsphere-api/apis/datacenter/v1alpha1"
	scheme "kubeform.dev/provider-vsphere-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DatacentersGetter has a method to return a DatacenterInterface.
// A group's client should implement this interface.
type DatacentersGetter interface {
	Datacenters(namespace string) DatacenterInterface
}

// DatacenterInterface has methods to work with Datacenter resources.
type DatacenterInterface interface {
	Create(ctx context.Context, datacenter *v1alpha1.Datacenter, opts v1.CreateOptions) (*v1alpha1.Datacenter, error)
	Update(ctx context.Context, datacenter *v1alpha1.Datacenter, opts v1.UpdateOptions) (*v1alpha1.Datacenter, error)
	UpdateStatus(ctx context.Context, datacenter *v1alpha1.Datacenter, opts v1.UpdateOptions) (*v1alpha1.Datacenter, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Datacenter, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DatacenterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Datacenter, err error)
	DatacenterExpansion
}

// datacenters implements DatacenterInterface
type datacenters struct {
	client rest.Interface
	ns     string
}

// newDatacenters returns a Datacenters
func newDatacenters(c *DatacenterV1alpha1Client, namespace string) *datacenters {
	return &datacenters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the datacenter, and returns the corresponding datacenter object, and an error if there is any.
func (c *datacenters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Datacenter, err error) {
	result = &v1alpha1.Datacenter{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("datacenters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Datacenters that match those selectors.
func (c *datacenters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DatacenterList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DatacenterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("datacenters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested datacenters.
func (c *datacenters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("datacenters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a datacenter and creates it.  Returns the server's representation of the datacenter, and an error, if there is any.
func (c *datacenters) Create(ctx context.Context, datacenter *v1alpha1.Datacenter, opts v1.CreateOptions) (result *v1alpha1.Datacenter, err error) {
	result = &v1alpha1.Datacenter{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("datacenters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(datacenter).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a datacenter and updates it. Returns the server's representation of the datacenter, and an error, if there is any.
func (c *datacenters) Update(ctx context.Context, datacenter *v1alpha1.Datacenter, opts v1.UpdateOptions) (result *v1alpha1.Datacenter, err error) {
	result = &v1alpha1.Datacenter{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("datacenters").
		Name(datacenter.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(datacenter).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *datacenters) UpdateStatus(ctx context.Context, datacenter *v1alpha1.Datacenter, opts v1.UpdateOptions) (result *v1alpha1.Datacenter, err error) {
	result = &v1alpha1.Datacenter{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("datacenters").
		Name(datacenter.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(datacenter).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the datacenter and deletes it. Returns an error if one occurs.
func (c *datacenters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("datacenters").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *datacenters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("datacenters").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched datacenter.
func (c *datacenters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Datacenter, err error) {
	result = &v1alpha1.Datacenter{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("datacenters").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
