apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: vsphere.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: hosts.host.vsphere.kubeform.com
spec:
  group: host.vsphere.kubeform.com
  names:
    kind: Host
    listKind: HostList
    plural: hosts
    singular: host
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  cluster:
                    description: ID of the vSphere cluster the host will belong to.
                    type: string
                  clusterManaged:
                    description: Must be set if host is a member of a managed compute_cluster
                      resource.
                    type: boolean
                  connected:
                    description: Set the state of the host. If set to false then the
                      host will be asked to disconnect.
                    type: boolean
                  datacenter:
                    description: ID of the vSphere datacenter the host will belong
                      to.
                    type: string
                  force:
                    description: Force add the host to vsphere, even if it's already
                      managed by a different vSphere instance.
                    type: boolean
                  hostname:
                    description: FQDN or IP address of the host.
                    type: string
                  id:
                    type: string
                  license:
                    description: License key that will be applied to this host.
                    type: string
                  lockdown:
                    description: Set the host's lockdown status. Default is disabled.
                      Valid options are 'disabled', 'normal', 'strict'
                    type: string
                  maintenance:
                    description: Set the host's maintenance mode. Default is false
                    type: boolean
                  thumbprint:
                    description: Host's certificate SHA-1 thumbprint. If not set then
                      the CA that signed the host's certificate must be trusted.
                    type: string
                  username:
                    description: Username of the administration account of the host.
                    type: string
                required:
                - hostname
                - username
                type: object
              secretRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              state:
                properties:
                  cluster:
                    description: ID of the vSphere cluster the host will belong to.
                    type: string
                  clusterManaged:
                    description: Must be set if host is a member of a managed compute_cluster
                      resource.
                    type: boolean
                  connected:
                    description: Set the state of the host. If set to false then the
                      host will be asked to disconnect.
                    type: boolean
                  datacenter:
                    description: ID of the vSphere datacenter the host will belong
                      to.
                    type: string
                  force:
                    description: Force add the host to vsphere, even if it's already
                      managed by a different vSphere instance.
                    type: boolean
                  hostname:
                    description: FQDN or IP address of the host.
                    type: string
                  id:
                    type: string
                  license:
                    description: License key that will be applied to this host.
                    type: string
                  lockdown:
                    description: Set the host's lockdown status. Default is disabled.
                      Valid options are 'disabled', 'normal', 'strict'
                    type: string
                  maintenance:
                    description: Set the host's maintenance mode. Default is false
                    type: boolean
                  thumbprint:
                    description: Host's certificate SHA-1 thumbprint. If not set then
                      the CA that signed the host's certificate must be trusted.
                    type: string
                  username:
                    description: Username of the administration account of the host.
                    type: string
                required:
                - hostname
                - username
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
