apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: vsphere.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: virtualswitches.host.vsphere.kubeform.com
spec:
  group: host.vsphere.kubeform.com
  names:
    kind: VirtualSwitch
    listKind: VirtualSwitchList
    plural: virtualswitches
    singular: virtualswitch
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  activeNics:
                    description: List of active network adapters used for load balancing.
                    items:
                      type: string
                    type: array
                  allowForgedTransmits:
                    description: Controls whether or not the virtual network adapter
                      is allowed to send network traffic with a different MAC address
                      than that of its own.
                    type: boolean
                  allowMACChanges:
                    description: Controls whether or not the Media Access Control
                      (MAC) address can be changed.
                    type: boolean
                  allowPromiscuous:
                    description: Enable promiscuous mode on the network. This flag
                      indicates whether or not all traffic is seen on a given port.
                    type: boolean
                  beaconInterval:
                    description: Determines how often, in seconds, a beacon should
                      be sent to probe for the validity of a link.
                    format: int64
                    type: integer
                  checkBeacon:
                    description: Enable beacon probing. Requires that the vSwitch
                      has been configured to use a beacon. If disabled, link status
                      is used only.
                    type: boolean
                  failback:
                    description: If true, the teaming policy will re-activate failed
                      interfaces higher in precedence when they come back up.
                    type: boolean
                  hostSystemID:
                    description: The managed object ID of the host to set the virtual
                      switch up on.
                    type: string
                  id:
                    type: string
                  linkDiscoveryOperation:
                    description: Whether to advertise or listen for link discovery.
                      Valid values are advertise, both, listen, and none.
                    type: string
                  linkDiscoveryProtocol:
                    description: The discovery protocol type. Valid values are cdp
                      and lldp.
                    type: string
                  mtu:
                    description: The maximum transmission unit (MTU) of the virtual
                      switch in bytes.
                    format: int64
                    type: integer
                  name:
                    description: The name of the virtual switch.
                    type: string
                  networkAdapters:
                    description: The list of network adapters to bind to this virtual
                      switch.
                    items:
                      type: string
                    type: array
                  notifySwitches:
                    description: If true, the teaming policy will notify the broadcast
                      network of a NIC failover, triggering cache updates.
                    type: boolean
                  numberOfPorts:
                    description: The number of ports that this virtual switch is configured
                      to use.
                    format: int64
                    type: integer
                  shapingAverageBandwidth:
                    description: The average bandwidth in bits per second if traffic
                      shaping is enabled.
                    format: int64
                    type: integer
                  shapingBurstSize:
                    description: The maximum burst size allowed in bytes if traffic
                      shaping is enabled.
                    format: int64
                    type: integer
                  shapingEnabled:
                    description: Enable traffic shaping on this virtual switch or
                      port group.
                    type: boolean
                  shapingPeakBandwidth:
                    description: The peak bandwidth during bursts in bits per second
                      if traffic shaping is enabled.
                    format: int64
                    type: integer
                  standbyNics:
                    description: List of standby network adapters used for failover.
                    items:
                      type: string
                    type: array
                  teamingPolicy:
                    description: The network adapter teaming policy. Can be one of
                      loadbalance_ip, loadbalance_srcmac, loadbalance_srcid, or failover_explicit.
                    type: string
                required:
                - activeNics
                - hostSystemID
                - name
                - networkAdapters
                - standbyNics
                type: object
              state:
                properties:
                  activeNics:
                    description: List of active network adapters used for load balancing.
                    items:
                      type: string
                    type: array
                  allowForgedTransmits:
                    description: Controls whether or not the virtual network adapter
                      is allowed to send network traffic with a different MAC address
                      than that of its own.
                    type: boolean
                  allowMACChanges:
                    description: Controls whether or not the Media Access Control
                      (MAC) address can be changed.
                    type: boolean
                  allowPromiscuous:
                    description: Enable promiscuous mode on the network. This flag
                      indicates whether or not all traffic is seen on a given port.
                    type: boolean
                  beaconInterval:
                    description: Determines how often, in seconds, a beacon should
                      be sent to probe for the validity of a link.
                    format: int64
                    type: integer
                  checkBeacon:
                    description: Enable beacon probing. Requires that the vSwitch
                      has been configured to use a beacon. If disabled, link status
                      is used only.
                    type: boolean
                  failback:
                    description: If true, the teaming policy will re-activate failed
                      interfaces higher in precedence when they come back up.
                    type: boolean
                  hostSystemID:
                    description: The managed object ID of the host to set the virtual
                      switch up on.
                    type: string
                  id:
                    type: string
                  linkDiscoveryOperation:
                    description: Whether to advertise or listen for link discovery.
                      Valid values are advertise, both, listen, and none.
                    type: string
                  linkDiscoveryProtocol:
                    description: The discovery protocol type. Valid values are cdp
                      and lldp.
                    type: string
                  mtu:
                    description: The maximum transmission unit (MTU) of the virtual
                      switch in bytes.
                    format: int64
                    type: integer
                  name:
                    description: The name of the virtual switch.
                    type: string
                  networkAdapters:
                    description: The list of network adapters to bind to this virtual
                      switch.
                    items:
                      type: string
                    type: array
                  notifySwitches:
                    description: If true, the teaming policy will notify the broadcast
                      network of a NIC failover, triggering cache updates.
                    type: boolean
                  numberOfPorts:
                    description: The number of ports that this virtual switch is configured
                      to use.
                    format: int64
                    type: integer
                  shapingAverageBandwidth:
                    description: The average bandwidth in bits per second if traffic
                      shaping is enabled.
                    format: int64
                    type: integer
                  shapingBurstSize:
                    description: The maximum burst size allowed in bytes if traffic
                      shaping is enabled.
                    format: int64
                    type: integer
                  shapingEnabled:
                    description: Enable traffic shaping on this virtual switch or
                      port group.
                    type: boolean
                  shapingPeakBandwidth:
                    description: The peak bandwidth during bursts in bits per second
                      if traffic shaping is enabled.
                    format: int64
                    type: integer
                  standbyNics:
                    description: List of standby network adapters used for failover.
                    items:
                      type: string
                    type: array
                  teamingPolicy:
                    description: The network adapter teaming policy. Can be one of
                      loadbalance_ip, loadbalance_srcmac, loadbalance_srcid, or failover_explicit.
                    type: string
                required:
                - activeNics
                - hostSystemID
                - name
                - networkAdapters
                - standbyNics
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
