apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: vsphere.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: entities.vapp.vsphere.kubeform.com
spec:
  group: vapp.vsphere.kubeform.com
  names:
    kind: Entity
    listKind: EntityList
    plural: entities
    singular: entity
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  containerID:
                    description: Managed object ID of the vApp container the entity
                      is a member of.
                    type: string
                  customAttributes:
                    additionalProperties:
                      type: string
                    description: A list of custom attributes to set on this resource.
                    type: object
                  id:
                    type: string
                  startAction:
                    description: How to start the entity. Valid settings are none
                      or powerOn. If set to none, then the entity does not participate
                      in auto-start.
                    type: string
                  startDelay:
                    description: Delay in seconds before continuing with the next
                      entity in the order of entities to be started.
                    format: int64
                    type: integer
                  startOrder:
                    description: Order to start and stop target in vApp.
                    format: int64
                    type: integer
                  stopAction:
                    description: Defines the stop action for the entity. Can be set
                      to none, powerOff, guestShutdown, or suspend. If set to none,
                      then the entity does not participate in auto-stop.
                    type: string
                  stopDelay:
                    description: Delay in seconds before continuing with the next
                      entity in the order of entities to be stopped.
                    format: int64
                    type: integer
                  tags:
                    description: A list of tag IDs to apply to this object.
                    items:
                      type: string
                    type: array
                  targetID:
                    description: Managed object ID of the entity to power on or power
                      off. This can be a virtual machine or a vApp.
                    type: string
                  waitForGuest:
                    description: Determines if the VM should be marked as being started
                      when VMware Tools are ready instead of waiting for start_delay.
                      This property has no effect for vApps.
                    type: boolean
                required:
                - containerID
                - targetID
                type: object
              state:
                properties:
                  containerID:
                    description: Managed object ID of the vApp container the entity
                      is a member of.
                    type: string
                  customAttributes:
                    additionalProperties:
                      type: string
                    description: A list of custom attributes to set on this resource.
                    type: object
                  id:
                    type: string
                  startAction:
                    description: How to start the entity. Valid settings are none
                      or powerOn. If set to none, then the entity does not participate
                      in auto-start.
                    type: string
                  startDelay:
                    description: Delay in seconds before continuing with the next
                      entity in the order of entities to be started.
                    format: int64
                    type: integer
                  startOrder:
                    description: Order to start and stop target in vApp.
                    format: int64
                    type: integer
                  stopAction:
                    description: Defines the stop action for the entity. Can be set
                      to none, powerOff, guestShutdown, or suspend. If set to none,
                      then the entity does not participate in auto-stop.
                    type: string
                  stopDelay:
                    description: Delay in seconds before continuing with the next
                      entity in the order of entities to be stopped.
                    format: int64
                    type: integer
                  tags:
                    description: A list of tag IDs to apply to this object.
                    items:
                      type: string
                    type: array
                  targetID:
                    description: Managed object ID of the entity to power on or power
                      off. This can be a virtual machine or a vApp.
                    type: string
                  waitForGuest:
                    description: Determines if the VM should be marked as being started
                      when VMware Tools are ready instead of waiting for start_delay.
                      This property has no effect for vApps.
                    type: boolean
                required:
                - containerID
                - targetID
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
