/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-vsphere-api/apis/content/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLibraryItems implements LibraryItemInterface
type FakeLibraryItems struct {
	Fake *FakeContentV1alpha1
	ns   string
}

var libraryitemsResource = schema.GroupVersionResource{Group: "content.vsphere.kubeform.com", Version: "v1alpha1", Resource: "libraryitems"}

var libraryitemsKind = schema.GroupVersionKind{Group: "content.vsphere.kubeform.com", Version: "v1alpha1", Kind: "LibraryItem"}

// Get takes name of the libraryItem, and returns the corresponding libraryItem object, and an error if there is any.
func (c *FakeLibraryItems) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.LibraryItem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(libraryitemsResource, c.ns, name), &v1alpha1.LibraryItem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LibraryItem), err
}

// List takes label and field selectors, and returns the list of LibraryItems that match those selectors.
func (c *FakeLibraryItems) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.LibraryItemList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(libraryitemsResource, libraryitemsKind, c.ns, opts), &v1alpha1.LibraryItemList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.LibraryItemList{ListMeta: obj.(*v1alpha1.LibraryItemList).ListMeta}
	for _, item := range obj.(*v1alpha1.LibraryItemList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested libraryItems.
func (c *FakeLibraryItems) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(libraryitemsResource, c.ns, opts))

}

// Create takes the representation of a libraryItem and creates it.  Returns the server's representation of the libraryItem, and an error, if there is any.
func (c *FakeLibraryItems) Create(ctx context.Context, libraryItem *v1alpha1.LibraryItem, opts v1.CreateOptions) (result *v1alpha1.LibraryItem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(libraryitemsResource, c.ns, libraryItem), &v1alpha1.LibraryItem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LibraryItem), err
}

// Update takes the representation of a libraryItem and updates it. Returns the server's representation of the libraryItem, and an error, if there is any.
func (c *FakeLibraryItems) Update(ctx context.Context, libraryItem *v1alpha1.LibraryItem, opts v1.UpdateOptions) (result *v1alpha1.LibraryItem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(libraryitemsResource, c.ns, libraryItem), &v1alpha1.LibraryItem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LibraryItem), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLibraryItems) UpdateStatus(ctx context.Context, libraryItem *v1alpha1.LibraryItem, opts v1.UpdateOptions) (*v1alpha1.LibraryItem, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(libraryitemsResource, "status", c.ns, libraryItem), &v1alpha1.LibraryItem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LibraryItem), err
}

// Delete takes name of the libraryItem and deletes it. Returns an error if one occurs.
func (c *FakeLibraryItems) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(libraryitemsResource, c.ns, name), &v1alpha1.LibraryItem{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLibraryItems) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(libraryitemsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.LibraryItemList{})
	return err
}

// Patch applies the patch and returns the patched libraryItem.
func (c *FakeLibraryItems) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.LibraryItem, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(libraryitemsResource, c.ns, name, pt, data, subresources...), &v1alpha1.LibraryItem{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.LibraryItem), err
}
