/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	entityv1alpha1 "kubeform.dev/provider-vsphere-api/apis/entity/v1alpha1"
	versioned "kubeform.dev/provider-vsphere-api/client/clientset/versioned"
	internalinterfaces "kubeform.dev/provider-vsphere-api/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubeform.dev/provider-vsphere-api/client/listers/entity/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// PermissionsInformer provides access to a shared informer and lister for
// Permissionses.
type PermissionsInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.PermissionsLister
}

type permissionsInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewPermissionsInformer constructs a new informer for Permissions type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPermissionsInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredPermissionsInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredPermissionsInformer constructs a new informer for Permissions type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPermissionsInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EntityV1alpha1().Permissionses(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EntityV1alpha1().Permissionses(namespace).Watch(context.TODO(), options)
			},
		},
		&entityv1alpha1.Permissions{},
		resyncPeriod,
		indexers,
	)
}

func (f *permissionsInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredPermissionsInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *permissionsInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&entityv1alpha1.Permissions{}, f.defaultInformer)
}

func (f *permissionsInformer) Lister() v1alpha1.PermissionsLister {
	return v1alpha1.NewPermissionsLister(f.Informer().GetIndexer())
}
