/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-vsphere-api/apis/dpm/v1alpha1"
	scheme "kubeform.dev/provider-vsphere-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HostOverridesGetter has a method to return a HostOverrideInterface.
// A group's client should implement this interface.
type HostOverridesGetter interface {
	HostOverrides(namespace string) HostOverrideInterface
}

// HostOverrideInterface has methods to work with HostOverride resources.
type HostOverrideInterface interface {
	Create(ctx context.Context, hostOverride *v1alpha1.HostOverride, opts v1.CreateOptions) (*v1alpha1.HostOverride, error)
	Update(ctx context.Context, hostOverride *v1alpha1.HostOverride, opts v1.UpdateOptions) (*v1alpha1.HostOverride, error)
	UpdateStatus(ctx context.Context, hostOverride *v1alpha1.HostOverride, opts v1.UpdateOptions) (*v1alpha1.HostOverride, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.HostOverride, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.HostOverrideList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HostOverride, err error)
	HostOverrideExpansion
}

// hostOverrides implements HostOverrideInterface
type hostOverrides struct {
	client rest.Interface
	ns     string
}

// newHostOverrides returns a HostOverrides
func newHostOverrides(c *DpmV1alpha1Client, namespace string) *hostOverrides {
	return &hostOverrides{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the hostOverride, and returns the corresponding hostOverride object, and an error if there is any.
func (c *hostOverrides) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HostOverride, err error) {
	result = &v1alpha1.HostOverride{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hostoverrides").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HostOverrides that match those selectors.
func (c *hostOverrides) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HostOverrideList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.HostOverrideList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hostoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested hostOverrides.
func (c *hostOverrides) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("hostoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a hostOverride and creates it.  Returns the server's representation of the hostOverride, and an error, if there is any.
func (c *hostOverrides) Create(ctx context.Context, hostOverride *v1alpha1.HostOverride, opts v1.CreateOptions) (result *v1alpha1.HostOverride, err error) {
	result = &v1alpha1.HostOverride{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("hostoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hostOverride).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a hostOverride and updates it. Returns the server's representation of the hostOverride, and an error, if there is any.
func (c *hostOverrides) Update(ctx context.Context, hostOverride *v1alpha1.HostOverride, opts v1.UpdateOptions) (result *v1alpha1.HostOverride, err error) {
	result = &v1alpha1.HostOverride{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hostoverrides").
		Name(hostOverride.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hostOverride).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *hostOverrides) UpdateStatus(ctx context.Context, hostOverride *v1alpha1.HostOverride, opts v1.UpdateOptions) (result *v1alpha1.HostOverride, err error) {
	result = &v1alpha1.HostOverride{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hostoverrides").
		Name(hostOverride.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(hostOverride).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the hostOverride and deletes it. Returns an error if one occurs.
func (c *hostOverrides) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hostoverrides").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *hostOverrides) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hostoverrides").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched hostOverride.
func (c *hostOverrides) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HostOverride, err error) {
	result = &v1alpha1.HostOverride{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("hostoverrides").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
