/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-vsphere-api/apis/virtual/v1alpha1"
	scheme "kubeform.dev/provider-vsphere-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MachineSnapshotsGetter has a method to return a MachineSnapshotInterface.
// A group's client should implement this interface.
type MachineSnapshotsGetter interface {
	MachineSnapshots(namespace string) MachineSnapshotInterface
}

// MachineSnapshotInterface has methods to work with MachineSnapshot resources.
type MachineSnapshotInterface interface {
	Create(ctx context.Context, machineSnapshot *v1alpha1.MachineSnapshot, opts v1.CreateOptions) (*v1alpha1.MachineSnapshot, error)
	Update(ctx context.Context, machineSnapshot *v1alpha1.MachineSnapshot, opts v1.UpdateOptions) (*v1alpha1.MachineSnapshot, error)
	UpdateStatus(ctx context.Context, machineSnapshot *v1alpha1.MachineSnapshot, opts v1.UpdateOptions) (*v1alpha1.MachineSnapshot, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.MachineSnapshot, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.MachineSnapshotList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MachineSnapshot, err error)
	MachineSnapshotExpansion
}

// machineSnapshots implements MachineSnapshotInterface
type machineSnapshots struct {
	client rest.Interface
	ns     string
}

// newMachineSnapshots returns a MachineSnapshots
func newMachineSnapshots(c *VirtualV1alpha1Client, namespace string) *machineSnapshots {
	return &machineSnapshots{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the machineSnapshot, and returns the corresponding machineSnapshot object, and an error if there is any.
func (c *machineSnapshots) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MachineSnapshot, err error) {
	result = &v1alpha1.MachineSnapshot{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("machinesnapshots").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MachineSnapshots that match those selectors.
func (c *machineSnapshots) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MachineSnapshotList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MachineSnapshotList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("machinesnapshots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested machineSnapshots.
func (c *machineSnapshots) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("machinesnapshots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a machineSnapshot and creates it.  Returns the server's representation of the machineSnapshot, and an error, if there is any.
func (c *machineSnapshots) Create(ctx context.Context, machineSnapshot *v1alpha1.MachineSnapshot, opts v1.CreateOptions) (result *v1alpha1.MachineSnapshot, err error) {
	result = &v1alpha1.MachineSnapshot{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("machinesnapshots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(machineSnapshot).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a machineSnapshot and updates it. Returns the server's representation of the machineSnapshot, and an error, if there is any.
func (c *machineSnapshots) Update(ctx context.Context, machineSnapshot *v1alpha1.MachineSnapshot, opts v1.UpdateOptions) (result *v1alpha1.MachineSnapshot, err error) {
	result = &v1alpha1.MachineSnapshot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("machinesnapshots").
		Name(machineSnapshot.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(machineSnapshot).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *machineSnapshots) UpdateStatus(ctx context.Context, machineSnapshot *v1alpha1.MachineSnapshot, opts v1.UpdateOptions) (result *v1alpha1.MachineSnapshot, err error) {
	result = &v1alpha1.MachineSnapshot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("machinesnapshots").
		Name(machineSnapshot.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(machineSnapshot).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the machineSnapshot and deletes it. Returns an error if one occurs.
func (c *machineSnapshots) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("machinesnapshots").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *machineSnapshots) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("machinesnapshots").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched machineSnapshot.
func (c *machineSnapshots) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MachineSnapshot, err error) {
	result = &v1alpha1.MachineSnapshot{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("machinesnapshots").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
