/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-vsphere-api/apis/storage/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDrsVmOverrides implements DrsVmOverrideInterface
type FakeDrsVmOverrides struct {
	Fake *FakeStorageV1alpha1
	ns   string
}

var drsvmoverridesResource = schema.GroupVersionResource{Group: "storage.vsphere.kubeform.com", Version: "v1alpha1", Resource: "drsvmoverrides"}

var drsvmoverridesKind = schema.GroupVersionKind{Group: "storage.vsphere.kubeform.com", Version: "v1alpha1", Kind: "DrsVmOverride"}

// Get takes name of the drsVmOverride, and returns the corresponding drsVmOverride object, and an error if there is any.
func (c *FakeDrsVmOverrides) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DrsVmOverride, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(drsvmoverridesResource, c.ns, name), &v1alpha1.DrsVmOverride{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DrsVmOverride), err
}

// List takes label and field selectors, and returns the list of DrsVmOverrides that match those selectors.
func (c *FakeDrsVmOverrides) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DrsVmOverrideList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(drsvmoverridesResource, drsvmoverridesKind, c.ns, opts), &v1alpha1.DrsVmOverrideList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DrsVmOverrideList{ListMeta: obj.(*v1alpha1.DrsVmOverrideList).ListMeta}
	for _, item := range obj.(*v1alpha1.DrsVmOverrideList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested drsVmOverrides.
func (c *FakeDrsVmOverrides) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(drsvmoverridesResource, c.ns, opts))

}

// Create takes the representation of a drsVmOverride and creates it.  Returns the server's representation of the drsVmOverride, and an error, if there is any.
func (c *FakeDrsVmOverrides) Create(ctx context.Context, drsVmOverride *v1alpha1.DrsVmOverride, opts v1.CreateOptions) (result *v1alpha1.DrsVmOverride, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(drsvmoverridesResource, c.ns, drsVmOverride), &v1alpha1.DrsVmOverride{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DrsVmOverride), err
}

// Update takes the representation of a drsVmOverride and updates it. Returns the server's representation of the drsVmOverride, and an error, if there is any.
func (c *FakeDrsVmOverrides) Update(ctx context.Context, drsVmOverride *v1alpha1.DrsVmOverride, opts v1.UpdateOptions) (result *v1alpha1.DrsVmOverride, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(drsvmoverridesResource, c.ns, drsVmOverride), &v1alpha1.DrsVmOverride{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DrsVmOverride), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDrsVmOverrides) UpdateStatus(ctx context.Context, drsVmOverride *v1alpha1.DrsVmOverride, opts v1.UpdateOptions) (*v1alpha1.DrsVmOverride, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(drsvmoverridesResource, "status", c.ns, drsVmOverride), &v1alpha1.DrsVmOverride{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DrsVmOverride), err
}

// Delete takes name of the drsVmOverride and deletes it. Returns an error if one occurs.
func (c *FakeDrsVmOverrides) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(drsvmoverridesResource, c.ns, name), &v1alpha1.DrsVmOverride{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDrsVmOverrides) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(drsvmoverridesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DrsVmOverrideList{})
	return err
}

// Patch applies the patch and returns the patched drsVmOverride.
func (c *FakeDrsVmOverrides) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DrsVmOverride, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(drsvmoverridesResource, c.ns, name, pt, data, subresources...), &v1alpha1.DrsVmOverride{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DrsVmOverride), err
}
